version: '3.8'

services:
  wallet_db:
    container_name: wallet_db
    image: "postgres:latest"
    ports:
      - "5432:${DATABASE_PORT:-5432}"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-test}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-test}
      POSTGRES_DB: ${DATABASE_NAME:-wallet}
    volumes:
      - .local/wallet-psql-data:/var/lib/postgresql/data

  game_db:
    container_name: game_db
    image: "postgres:latest"
    ports:
      - "5433:${DATABASE_PORT:-5432}"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-test}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-test}
      POSTGRES_DB: ${DATABASE_NAME:-game}
    volumes:
      - .local/game-psql-data:/var/lib/postgresql/data

#  rabbitmq:
#    container_name: 'game-wallet-rabbitmq'
#    image: rabbitmq:3-management-alpine
#    ports:
#      - 5672:5672
#      - 15672:15672
#    volumes:
#      - .local/rabbitmq/data:/var/lib/rabbitmq
#      - .local/rabbitmq/log:/var/log/rabbitmq
#    expose:
#      - 5672
#      - 15672
